-- require("plugins/misc/focus-config")
require("plugins/misc/indent-blanklines")
require("plugins/misc/telescope-config")
require("plugins/misc/toggleTermConfig")
require("plugins/misc/todo-comments")
require("plugins/misc/dim-config")
require("plugins/misc/winshift-config")
require("plugins/misc/goMove")
require("plugins/misc/whichkey-config")
require("plugins/misc/hop-config")
-- require("plugins/misc/conmenuConfig")
require("plugins/misc/close-buffers-config")
require("plugins/misc/spectre-config")
require("plugins/misc/cutlass-config")
require("plugins/misc/auto-pairs-config")
require("hlslens").setup()
