
require("plugins/ui/jabs-config")
require("plugins/ui/alpha")
require("plugins/ui/neotree-config")
-- require("plugins/ui/nvim-treeConfig")
require("plugins/ui/twilight-config")
require("plugins/ui/feline/feline-init")
require("plugins/ui/nightfoxConfig")
require("plugins/ui/scrollbar-config")
require("plugins/ui/aerial-config")
require("plugins/ui/project-config")
require("plugins/ui/neoscroll-config")
